BASE_TARIFF_DAY = 2.64
BASE_TARIFF_NIGHT = 1.32

HIGH_TARIFF_DAY = 4.32
HIGH_TARIFF_NIGHT = 2.16

TARIFF_LIMIT = 2000

FAKE_ADDITION_DAY = 100
FAKE_ADDITION_NIGHT = 80

TARIFF_DAY = BASE_TARIFF_DAY
TARIFF_NIGHT = BASE_TARIFF_NIGHT
TARIFFS = {
    "day": BASE_TARIFF_DAY,
    "night": BASE_TARIFF_NIGHT
}
ADJUSTMENT = {
    "day": FAKE_ADDITION_DAY,
    "night": FAKE_ADDITION_NIGHT
}
